theme = 'blowfish'
baseURL = 'https://blog.kamataryo.com'
defaultContentLanguage = 'ja'
enableRobotsTXT = true
paginate = 10
summaryLength = 0
languageCode = 'ja'
timeZone = 'Asia/Tokyo'
title = 'Antarctic Char'

[markup.goldmark.renderer]
  unsafe = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[permalinks]
  posts = '/posts/:slug/'
  pages = '/:slug/'

[author]
  name = 'kamataryo'
  image = 'img/author.png'
  bio = 'ウェブ開発者・ナチュラリスト'
  headline = '自然、野生生物、DIY、テック。'
  links = [
    { instagram = 'https://instagram.com/kamata.ryo'},
    { 'x-twitter' = 'https://twitter.com/kamataryo_'},
    { github = 'https://github.com/kamataryo'},
  ]



[taxonomies]
  category = 'categories'
  tag = 'tags'

# TODO: does it work?
googleAnalytics = 'G-VH8ND2E5KN'
