colorScheme = "avocado"
defaultAppearance = 'dark'
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = true

[header]
layout = 'fixed'

[footer]
showThemeAttribution = false
showScrollToTop = true

[homepage]
layout = "background"
homepageImage = "img/background.jpg"
showRecent = true
showRecentItems = 6
showMoreLink = true
cardView = true
# cardViewScreenWidth = true
layoutBackgroundBlur = true

[article]
showDate = true
showAuthor = false
showViews = true
showLikes = true
showHero = true
showTaxonomies = true

showWordCount = false
showReadingTime = false

[list]
showSummary = true
showCards = true
groupByYear = false
cardView = true

[taxonomy]
showTermCount = true

[firebase]
  apiKey = 'AIzaSyBYdXOHztjYIz7Bka4_XIrRFypIC9hjwkA'
  authDomain = 'blog-kamataryo-com.firebaseapp.com'
  projectId = 'blog-kamataryo-com'
  storageBucket = 'blog-kamataryo-com.appspot.com'
  messagingSenderId = '749454209474'
  appId = '1:749454209474:web:f6081c7ba865379a84a65b'
  measurementId = 'G-B3BKTNQZS3'
