# The Site Configuration

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
#--------------------------

title: Antarctic Char              # the main title

# the HTML language tag › https://www.w3.org/International/questions/qa-choosing-language-tags
tagline: >-                       # it will display as the sub-title
  自然、野生生物、ブッシュクラフト、テック。

lang: ja
# Import the theme
theme: jekyll-theme-chirpy

# Only if your site type is GitHub Project sites and doesn't have a custom domain,
# change below value to '/projectname'.
baseurl: ''

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Asia/Tokyo

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# --------------------------

description: >-                        # used by seo meta and the atom feed
  ポスト・アポカリプスに備えるブログ。自然、野生生物、ブッシュクラフト、テック。

# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: 'https://blog.kamataryo.com'

author: kamataryo                       # change to your full name

avatar: /assets/img/avatar.png          # support internet resources

github:
  username: kamataryo                   # change to your github username

twitter:
  username: kamataryo_                  # change to your twitter username

social:
  name: kamataryo                       # it will shows as the copyright owner in Footer
  email: mugil.cephalus+blog.kamataryo.com@gmail.com         # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://www.instagram.com/kamata.ryo
    - https://twitter.com/kamataryo_        # change to your twitter homepage
    - https://github.com/kamatarryo         # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# google_site_verification: google_meta_tag_verification # change to your verification string

#--------------------------

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone

google_analytics:
  id: 'G-GGCMESDNVR'          # Fill with your Google Analytics ID
  pv:
    proxy_endpoint:   # fill in the Google Analytics superProxy endpoint of Google App Engine
    cache_path:       # the local PV cache data, friendly to visitors from GFW region

disqus:
  comments: false  # boolean type, the global switch for posts comments.
  shortname: ''    # Fill with your Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname

geolonia:
  mapKey: bbd61bd3510942169387681310120552
google_site_verification: google_meta_tag_verification # change to your verification string
# --------------------------

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode: light # [light|dark]

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn: ''

# boolean type, the global switch for ToC in posts.
toc: true

paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order


defaults:
  -
    scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
      dynamic_title: true    # Hide title in mobile screens.

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - bin
  - gulpfile.js
  - node_modules
  # - '*.json'

sitemap_exclude:  # Sitemap will exclude the following items.
  fuzzy:
    - /assets/
  accurate:
    - /norobots/
    - /tabs/
    - /categories/
    - /tags/
    - /posts/
    - 404.html
    - feed.xml
    - sitemap.xml
    - robots.txt
    - redirects.json


jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
